repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: bash -c '(cd backend/api;pipenv run isort)'
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: bash -c '(cd backend/api;pipenv run flake8)'
        types: [python]
        exclude: setup.py|env.py
        pass_filenames: false

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: bash -c '(cd backend/api;pipenv run black)'
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: bash -c '(cd backend/api;pipenv run mypy)'
        types: [python]
        pass_filenames: true

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: bash -c '(cd backend/api;pipenv run pytest)'
        types: [python]
        verbose: true
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: (cd backend/api;pipenv run pytest --cov --cov-fail-under=100)
        types: [python]
        pass_filenames: false