version: "3.8"

services:
    app:
      build:
        context: ./frontend/app
      networks:
        - jomai-net
      volumes:
        - ./frontend/app/src:/usr/local/src/app/src
      ports:
        - "4200:4200"
      environment:
        - ENABLE_POLLING=${ENABLE_POLLING}

    api:
      build:
        context: ./backend/api
        args:
          DEBUG: 'false'
      networks:
        - jomai-net
      volumes:
        - web-data:/uploads
      depends_on:
        - db
      ports:
        - "8000:8000"
      environment:
        DB_HOST: db
        DB_USER: jomai
        DB_PASSWORD: N0n3ofUr8usiness!
        DB_NAME: jomai
      command: "uvicorn jomai.main:app --host 0.0.0.0 --port 8000 --reload"

    db:
      image: postgres:13.0-alpine
      networks:
        - jomai-net
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: jomai
        POSTGRES_USER: jomai
        POSTGRES_PASSWORD: N0n3ofUr8usiness!

networks:
  jomai-net:
    driver: bridge

volumes:
  web-data:
  db-data:
