version: "3.8"

services:
    api:
      build:
        context: ./backend/api
      networks:
        - jomai-net
      volumes:
        - ./backend/api/jomai:/usr/local/src/api/jomai
        - web-data:/uploads
      depends_on:
        - db
      ports:
        - "8000:8000"
      environment:
        DB_HOST: db
        DB_USER: jomai
        DB_PASSWORD: secret
        DB_NAME: jomai

    db:
      image: postgres:13.0-alpine
      networks:
        - jomai-net
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: N0n3ofUr8usiness!

networks:
  jomai-net:
    driver: bridge

volumes:
  web-data:
  db-data:
