"""applications count

Revision ID: 44981d4fccc0
Revises: fb2321eee08d
Create Date: 2020-10-22 12:23:13.294782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44981d4fccc0'
down_revision = 'fb2321eee08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('applications', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'applications')
    # ### end Alembic commands ###
