"""First migration

Revision ID: fb2321eee08d
Revises: First migration
Create Date: 2020-10-09 14:42:51.496875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb2321eee08d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("posted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_id"), "job", ["id"], unique=False)
    op.create_index(op.f("ix_job_title"), "job", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_title"), table_name="job")
    op.drop_index(op.f("ix_job_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
